version: "2"
services:

  atlas-server:
    build: .
    image: wbaa/rokku-dev-apache-atlas
    ports:
      - "21000:21000"
    depends_on:
      - "zookeeper"
      - "kafka"
      - "cassandra"
      - "elasticsearch"
  cassandra:
    image: cassandra:latest
    hostname: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - "9200:9200"
      - "9300:9300"
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"  
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "create_events:1:1,delete_events:1:1,ATLAS_HOOK:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper  
